[workspace]
members = [
    "bitcoin",
    "common",
    "merkle-tree",
]
resolver = "2"

# [dependencies]
# hex = "0.4.3"
# hex-literal = "0.4.1"
# ripemd = "0.1.3"
# sha2 = "0.10.8"
[workspace.dependencies]
sha2 = "0.10.8"
