[package]
name = "bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
hmac = "0.12.1"
pbkdf2 = "0.12.2"
ripemd = "0.1.3"
sha2 = "0.10.8"
